import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
    { path: '', redirectTo: '/welcome', pathMatch: "full" },
    { path: 'welcome',
    loadComponent: () => import('./components/welcome/welcome.component').then(c => c.WelcomeComponent) },
    { path: 'login',
    loadComponent: () => import('./components/login/login.component').then(c => c.LoginComponent) },
    { path: 'registro',
    loadComponent: () => import('./components/register/register.component').then(c => c.RegisterComponent) },
    { path: 'home',
        canActivate: [authGuard],
        loadComponent: () => import('./components/home/home.component').then(c => c.HomeComponent) },
    { path: 'usuarios',
        canActivate: [authGuard],
        loadComponent: () => import('./components/usuarios/usuarios.component').then(c => c.UsuariosComponent) },
    { path: 'turnos/administrador',
        canActivate: [authGuard],
        loadComponent: () => import('./components/turnos/turnos.component').then(c => c.TurnosComponent) },
    { path: 'turnos/especialista',
        canActivate: [authGuard],
        loadComponent: () => import('./components/turnos-especialista/turnos-especialista.component').then(c => c.TurnosEspecialistaComponent) },
    { path: 'turnos/paciente',
        canActivate: [authGuard],
        loadComponent: () => import('./components/turnos-paciente/turnos-paciente.component').then(c => c.TurnosPacienteComponent) },
    { path: 'turnos/nuevo',
        canActivate: [authGuard],
        loadComponent: () => import('./components/alta-turnos/alta-turnos.component').then(c => c.AltaTurnosComponent) },
    { path: 'perfil',
        canActivate: [authGuard],
        loadComponent: () => import('./components/perfil/perfil.component').then(c => c.PerfilComponent) },
    { path: 'horarios',
        canActivate: [authGuard],
        loadComponent: () => import('./components/horarios-especialista/horarios-especialista.component').then(c => c.HorariosEspecialistaComponent) },
    { path: 'historiaclinica',
        canActivate: [authGuard],
        loadComponent: () => import('./components/historia-clinica/historia-clinica.component').then(c => c.HistoriaClinicaComponent) },
    { path: 'informes',
        canActivate: [authGuard],
        loadComponent: () => import('./components/informes/informes.component').then(c => c.InformesComponent) },
    { path: 'pacientes',
        canActivate: [authGuard],
        loadComponent: () => import('./components/pacientes/pacientes.component').then(c => c.PacientesComponent) }
];
